# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Skin', [dirname(__file__)])
        except ImportError:
            import _Skin
            return _Skin
        if fp is not None:
            try:
                _mod = imp.load_module('_Skin', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Skin = swig_import_helper()
    del swig_import_helper
else:
    import _Skin
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class Skin(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Skin, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Skin, name)
    __repr__ = _swig_repr
    __swig_setmethods__["m_rou_lipid"] = _Skin.Skin_m_rou_lipid_set
    __swig_getmethods__["m_rou_lipid"] = _Skin.Skin_m_rou_lipid_get
    if _newclass:m_rou_lipid = _swig_property(_Skin.Skin_m_rou_lipid_get, _Skin.Skin_m_rou_lipid_set)
    __swig_setmethods__["m_rou_keratin"] = _Skin.Skin_m_rou_keratin_set
    __swig_getmethods__["m_rou_keratin"] = _Skin.Skin_m_rou_keratin_get
    if _newclass:m_rou_keratin = _swig_property(_Skin.Skin_m_rou_keratin_get, _Skin.Skin_m_rou_keratin_set)
    __swig_setmethods__["m_rou_water"] = _Skin.Skin_m_rou_water_set
    __swig_getmethods__["m_rou_water"] = _Skin.Skin_m_rou_water_get
    if _newclass:m_rou_water = _swig_property(_Skin.Skin_m_rou_water_get, _Skin.Skin_m_rou_water_set)
    __swig_setmethods__["m_mw"] = _Skin.Skin_m_mw_set
    __swig_getmethods__["m_mw"] = _Skin.Skin_m_mw_get
    if _newclass:m_mw = _swig_property(_Skin.Skin_m_mw_get, _Skin.Skin_m_mw_set)
    __swig_setmethods__["m_concSource"] = _Skin.Skin_m_concSource_set
    __swig_getmethods__["m_concSource"] = _Skin.Skin_m_concSource_get
    if _newclass:m_concSource = _swig_property(_Skin.Skin_m_concSource_get, _Skin.Skin_m_concSource_set)
    __swig_setmethods__["m_DSource"] = _Skin.Skin_m_DSource_set
    __swig_getmethods__["m_DSource"] = _Skin.Skin_m_DSource_get
    if _newclass:m_DSource = _swig_property(_Skin.Skin_m_DSource_get, _Skin.Skin_m_DSource_set)
    __swig_setmethods__["m_K_ow"] = _Skin.Skin_m_K_ow_set
    __swig_getmethods__["m_K_ow"] = _Skin.Skin_m_K_ow_get
    if _newclass:m_K_ow = _swig_property(_Skin.Skin_m_K_ow_get, _Skin.Skin_m_K_ow_set)
    __swig_setmethods__["m_T"] = _Skin.Skin_m_T_set
    __swig_getmethods__["m_T"] = _Skin.Skin_m_T_get
    if _newclass:m_T = _swig_property(_Skin.Skin_m_T_get, _Skin.Skin_m_T_set)
    __swig_setmethods__["m_eta"] = _Skin.Skin_m_eta_set
    __swig_getmethods__["m_eta"] = _Skin.Skin_m_eta_get
    if _newclass:m_eta = _swig_property(_Skin.Skin_m_eta_get, _Skin.Skin_m_eta_set)
    __swig_setmethods__["m_dz"] = _Skin.Skin_m_dz_set
    __swig_getmethods__["m_dz"] = _Skin.Skin_m_dz_get
    if _newclass:m_dz = _swig_property(_Skin.Skin_m_dz_get, _Skin.Skin_m_dz_set)
    __swig_setmethods__["m_x_length"] = _Skin.Skin_m_x_length_set
    __swig_getmethods__["m_x_length"] = _Skin.Skin_m_x_length_get
    if _newclass:m_x_length = _swig_property(_Skin.Skin_m_x_length_get, _Skin.Skin_m_x_length_set)
    __swig_setmethods__["m_y_length"] = _Skin.Skin_m_y_length_set
    __swig_getmethods__["m_y_length"] = _Skin.Skin_m_y_length_get
    if _newclass:m_y_length = _swig_property(_Skin.Skin_m_y_length_get, _Skin.Skin_m_y_length_set)
    __swig_setmethods__["m_x_length_ve"] = _Skin.Skin_m_x_length_ve_set
    __swig_getmethods__["m_x_length_ve"] = _Skin.Skin_m_x_length_ve_get
    if _newclass:m_x_length_ve = _swig_property(_Skin.Skin_m_x_length_ve_get, _Skin.Skin_m_x_length_ve_set)
    __swig_setmethods__["m_boundary_cond"] = _Skin.Skin_m_boundary_cond_set
    __swig_getmethods__["m_boundary_cond"] = _Skin.Skin_m_boundary_cond_get
    if _newclass:m_boundary_cond = _swig_property(_Skin.Skin_m_boundary_cond_get, _Skin.Skin_m_boundary_cond_set)
    __swig_setmethods__["m_dim_vh"] = _Skin.Skin_m_dim_vh_set
    __swig_getmethods__["m_dim_vh"] = _Skin.Skin_m_dim_vh_get
    if _newclass:m_dim_vh = _swig_property(_Skin.Skin_m_dim_vh_get, _Skin.Skin_m_dim_vh_set)
    __swig_setmethods__["m_dim_sc"] = _Skin.Skin_m_dim_sc_set
    __swig_getmethods__["m_dim_sc"] = _Skin.Skin_m_dim_sc_get
    if _newclass:m_dim_sc = _swig_property(_Skin.Skin_m_dim_sc_get, _Skin.Skin_m_dim_sc_set)
    __swig_setmethods__["m_dim_ve"] = _Skin.Skin_m_dim_ve_set
    __swig_getmethods__["m_dim_ve"] = _Skin.Skin_m_dim_ve_get
    if _newclass:m_dim_ve = _swig_property(_Skin.Skin_m_dim_ve_get, _Skin.Skin_m_dim_ve_set)
    __swig_setmethods__["m_dim_de"] = _Skin.Skin_m_dim_de_set
    __swig_getmethods__["m_dim_de"] = _Skin.Skin_m_dim_de_get
    if _newclass:m_dim_de = _swig_property(_Skin.Skin_m_dim_de_get, _Skin.Skin_m_dim_de_set)
    __swig_setmethods__["m_dim_bd"] = _Skin.Skin_m_dim_bd_set
    __swig_getmethods__["m_dim_bd"] = _Skin.Skin_m_dim_bd_get
    if _newclass:m_dim_bd = _swig_property(_Skin.Skin_m_dim_bd_get, _Skin.Skin_m_dim_bd_set)
    __swig_setmethods__["m_dim_all"] = _Skin.Skin_m_dim_all_set
    __swig_getmethods__["m_dim_all"] = _Skin.Skin_m_dim_all_get
    if _newclass:m_dim_all = _swig_property(_Skin.Skin_m_dim_all_get, _Skin.Skin_m_dim_all_set)
    __swig_setmethods__["m_gsl_ode_Jacobian"] = _Skin.Skin_m_gsl_ode_Jacobian_set
    __swig_getmethods__["m_gsl_ode_Jacobian"] = _Skin.Skin_m_gsl_ode_Jacobian_get
    if _newclass:m_gsl_ode_Jacobian = _swig_property(_Skin.Skin_m_gsl_ode_Jacobian_get, _Skin.Skin_m_gsl_ode_Jacobian_set)
    __swig_setmethods__["m_gridVehicle"] = _Skin.Skin_m_gridVehicle_set
    __swig_getmethods__["m_gridVehicle"] = _Skin.Skin_m_gridVehicle_get
    if _newclass:m_gridVehicle = _swig_property(_Skin.Skin_m_gridVehicle_get, _Skin.Skin_m_gridVehicle_set)
    __swig_setmethods__["m_gridSink"] = _Skin.Skin_m_gridSink_set
    __swig_getmethods__["m_gridSink"] = _Skin.Skin_m_gridSink_get
    if _newclass:m_gridSink = _swig_property(_Skin.Skin_m_gridSink_get, _Skin.Skin_m_gridSink_set)
    __swig_setmethods__["m_Vehicle_area"] = _Skin.Skin_m_Vehicle_area_set
    __swig_getmethods__["m_Vehicle_area"] = _Skin.Skin_m_Vehicle_area_get
    if _newclass:m_Vehicle_area = _swig_property(_Skin.Skin_m_Vehicle_area_get, _Skin.Skin_m_Vehicle_area_set)
    __swig_setmethods__["m_bInfSrc"] = _Skin.Skin_m_bInfSrc_set
    __swig_getmethods__["m_bInfSrc"] = _Skin.Skin_m_bInfSrc_get
    if _newclass:m_bInfSrc = _swig_property(_Skin.Skin_m_bInfSrc_get, _Skin.Skin_m_bInfSrc_set)
    __swig_setmethods__["m_StraCorn"] = _Skin.Skin_m_StraCorn_set
    __swig_getmethods__["m_StraCorn"] = _Skin.Skin_m_StraCorn_get
    if _newclass:m_StraCorn = _swig_property(_Skin.Skin_m_StraCorn_get, _Skin.Skin_m_StraCorn_set)
    __swig_setmethods__["m_ViaEpd"] = _Skin.Skin_m_ViaEpd_set
    __swig_getmethods__["m_ViaEpd"] = _Skin.Skin_m_ViaEpd_get
    if _newclass:m_ViaEpd = _swig_property(_Skin.Skin_m_ViaEpd_get, _Skin.Skin_m_ViaEpd_set)
    __swig_setmethods__["m_Dermis"] = _Skin.Skin_m_Dermis_set
    __swig_getmethods__["m_Dermis"] = _Skin.Skin_m_Dermis_get
    if _newclass:m_Dermis = _swig_property(_Skin.Skin_m_Dermis_get, _Skin.Skin_m_Dermis_set)
    __swig_setmethods__["m_Blood"] = _Skin.Skin_m_Blood_set
    __swig_getmethods__["m_Blood"] = _Skin.Skin_m_Blood_get
    if _newclass:m_Blood = _swig_property(_Skin.Skin_m_Blood_get, _Skin.Skin_m_Blood_set)
    def __init__(self): 
        this = _Skin.new_Skin()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _Skin.delete_Skin
    __del__ = lambda self : None;
    def Init(self, *args): return _Skin.Skin_Init(self, *args)
    def Release(self): return _Skin.Skin_Release(self)
    def diffuseMoL(self, *args): return _Skin.Skin_diffuseMoL(self, *args)
    def resetVehicle(self, *args): return _Skin.Skin_resetVehicle(self, *args)
    def removeVehicle(self): return _Skin.Skin_removeVehicle(self)
    def compFlux_2sc(self): return _Skin.Skin_compFlux_2sc(self)
    def compFlux_sc2down(self): return _Skin.Skin_compFlux_sc2down(self)
    def compFlux_ve2down(self): return _Skin.Skin_compFlux_ve2down(self)
    def compFlux_de2down(self): return _Skin.Skin_compFlux_de2down(self)
    def compODE_dydt(self, *args): return _Skin.Skin_compODE_dydt(self, *args)
    __swig_getmethods__["static_cvODE"] = lambda x: _Skin.Skin_static_cvODE
    if _newclass:static_cvODE = staticmethod(_Skin.Skin_static_cvODE)
    def getNLayerXSc(self): return _Skin.Skin_getNLayerXSc(self)
    def getNGridsXSc(self): return _Skin.Skin_getNGridsXSc(self)
    def getNGridsYSc(self): return _Skin.Skin_getNGridsYSc(self)
    def get1DConcSC(self, *args): return _Skin.Skin_get1DConcSC(self, *args)
    def get1DCoordSC(self, *args): return _Skin.Skin_get1DCoordSC(self, *args)
    def getGridsConc(self, *args): return _Skin.Skin_getGridsConc(self, *args)
    def displayGrids(self): return _Skin.Skin_displayGrids(self)
    def saveGrids(self, *args): return _Skin.Skin_saveGrids(self, *args)
    def saveVehicle(self, *args): return _Skin.Skin_saveVehicle(self, *args)
    def getXCoord(self, *args): return _Skin.Skin_getXCoord(self, *args)
    def getYCoord(self, *args): return _Skin.Skin_getYCoord(self, *args)
    def saveCoord(self, *args): return _Skin.Skin_saveCoord(self, *args)
Skin_swigregister = _Skin.Skin_swigregister
Skin_swigregister(Skin)

def Skin_static_cvODE(*args):
  return _Skin.Skin_static_cvODE(*args)
Skin_static_cvODE = _Skin.Skin_static_cvODE

# This file is compatible with both classic and new-style classes.


